from datetime import datetime

URL = "https://cart.spfcticket.net/saopaulofcxbotafogorj_25_09"

SECTIONS_WITHOUT_DISCOUNT = [
    "ARQUIBANCADA NORTE OREO", 
    "ARQUIBANCADA SUL DIAMANTE NEGRO",
    "CADEIRA SUPERIOR NORTE OREO",
    "CADEIRA SUPERIOR SUL DIAMANTE NEGRO", 
    "CADEIRA ESPECIAL OESTE OURO BRANCO",
    "CAMAROTE CORPORATIVO SPFC"
]

USERNAME: str = "seu_username"
PASSWORD: str = "sua_senha"

NUMBER_OF_GUESTS = 1

IS_SCHEDULED = True
SCHEDULED_TIMESTAMP = datetime(2023, 8, 28, 21, 59)

